import React, { Component } from 'react';
import Task from './Task'

class List extends Component {

  handleCheck = (index) => {
    const newList = this.props.list.slice();
    //check or uncheck the box at the given index
    newList[index].isChecked = newList[index].isChecked ? false: true;
    //update the list state in the parent (App) component
    this.props.changeList(newList);
  }

  handleDeleteClick = (index) => {
    const newList = this.props.list.slice();
    //delete the task at the given index
    newList.splice(index, 1);
    //update the list state in the parent (App) component
    this.props.changeList(newList);
  }

  reorderList = (startId, endId) => {
    const newList = this.props.list.slice();
    //find the indecies of the tasks with given ids
    const taskIdArr = newList.map(task => task.id)
    const startIndex = taskIdArr.indexOf(startId)
    const endIndex = taskIdArr.indexOf(endId)
    /*
    If startIndex > endIndex, moves start task to before the end task.
    If startIndex < endIndex, moves start task to after the end task.
    */
    newList.splice(endIndex, 0, newList.splice(startIndex,1)[0]);
    //update the list state in the parent (App) component
    this.props.changeList(newList);
    return;
  }


  render() {
    //Each task has a unique key/id generated by lodash/uniqueId
    return this.props.list.map((item,index) => {
      return (
        <Task
        key = {item.id}
        index = {index}
        reorderList = {this.reorderList}
        isChecked = {item.isChecked}
        inputValue = {item.inputValue}
        id = {item.id}
        onBoxClick = {this.handleCheck}
        onDeleteClick = {this.handleDeleteClick}
        />
      );
    });
  }
}


export default List;
